/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-06-03 10:26:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddTravelGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/javaProgramming/Tour&Travel2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ExpensesProject/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/html_basic.tld", Long.valueOf(1479140598000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.14.jar", Long.valueOf(1747127572674L));
    _jspx_dependants.put("jar:file:/C:/javaProgramming/Tour&Travel2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ExpensesProject/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/jsf_core.tld", Long.valueOf(1479140578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass_005fprependId;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005ffor_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass_005fprependId = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005ffor_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass_005fprependId.release();
    _005fjspx_005ftagPool_005fh_005foutputLabel_0026_005fvalue_005fstyleClass_005ffor_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyleClass_005fid.release();
    _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_1237257437_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html lang=\"en\">\r\n");
          out.write("<head>\r\n");
          out.write("    <meta charset=\"UTF-8\">\r\n");
          out.write("    <title>Add Travel Group</title>\r\n");
          out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
          out.write("</head>\r\n");
          out.write("<body class=\"bg-black min-h-screen font-sans text-gray-900 flex flex-col items-center justify-start p-6 space-y-6\">\r\n");
          out.write("\r\n");
          out.write("    <!-- Dashboard -->\r\n");
          out.write("    <div class=\"w-full max-w-4xl\">\r\n");
          out.write("        ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "DashBoard.jsp", out, false);
          out.write("\r\n");
          out.write("    </div>\r\n");
          out.write("\r\n");
          out.write("    <!-- Travel Group Form -->\r\n");
          out.write("    <div class=\"max-w-4xl w-full bg-white rounded-md shadow-md p-6\">\r\n");
          out.write("        <header class=\"text-center mb-6\">\r\n");
          out.write("            <h2 class=\"text-3xl font-bold text-green-700\">Create New Travel Group</h2>\r\n");
          out.write("            <p class=\"text-gray-600\">Enter group details below</p>\r\n");
          out.write("        </header>\r\n");
          out.write("\r\n");
          out.write("        ");
          if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    </div>\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    com.sun.faces.taglib.html_basic.FormTag _jspx_th_h_005fform_005f0 = new com.sun.faces.taglib.html_basic.FormTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fform_005f0);
    try {
      _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /AddTravelGroup.jsp(27,8) name = prependId type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
      _jspx_th_h_005fform_005f0.setPrependId(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(27,8) 'false'",_jsp_getExpressionFactory().createValueExpression("false",boolean.class)));
      // /AddTravelGroup.jsp(27,8) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fform_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(27,8) 'space-y-4'",_jsp_getExpressionFactory().createValueExpression("space-y-4",java.lang.String.class)));
      _jspx_th_h_005fform_005f0.setJspId("jsp_1237257437_1");
      int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("            <!-- Created By -->\r\n");
          out.write("            <div>\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- Group Name -->\r\n");
          out.write("            <div>\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- Start Date -->\r\n");
          out.write("            <div>\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- End Date -->\r\n");
          out.write("            <div>\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f3(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f3(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- Initial Amount -->\r\n");
          out.write("            <div>\r\n");
          out.write("                ");
          if (_jspx_meth_h_005foutputLabel_005f4(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_h_005finputText_005f4(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("\r\n");
          out.write("            <!-- Submit Button -->\r\n");
          out.write("            <div class=\"text-center mt-4\">\r\n");
          out.write("                ");
          if (_jspx_meth_h_005fcommandButton_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fform_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f0 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f0);
    try {
      _jspx_th_h_005foutputLabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(30,16) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setFor(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(30,16) 'createdBy'",_jsp_getExpressionFactory().createValueExpression("createdBy",java.lang.String.class)));
      // /AddTravelGroup.jsp(30,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(30,16) 'Created By'",_jsp_getExpressionFactory().createValueExpression("Created By",java.lang.Object.class)));
      // /AddTravelGroup.jsp(30,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(30,16) 'block mb-1 text-gray-700 font-semibold'",_jsp_getExpressionFactory().createValueExpression("block mb-1 text-gray-700 font-semibold",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f0.setJspId("jsp_1237257437_2");
      int _jspx_eval_h_005foutputLabel_005f0 = _jspx_th_h_005foutputLabel_005f0.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f0 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f0);
    try {
      _jspx_th_h_005finputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(31,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setId("createdBy");
      // /AddTravelGroup.jsp(31,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(31,16) '#{travelGroup.createdBy}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{travelGroup.createdBy}",java.lang.Object.class)));
      // /AddTravelGroup.jsp(31,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(31,16) 'w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400'",_jsp_getExpressionFactory().createValueExpression("w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400",java.lang.String.class)));
      _jspx_th_h_005finputText_005f0.setJspId("jsp_1237257437_3");
      int _jspx_eval_h_005finputText_005f0 = _jspx_th_h_005finputText_005f0.doStartTag();
      if (_jspx_th_h_005finputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f1 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f1);
    try {
      _jspx_th_h_005foutputLabel_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(37,16) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f1.setFor(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(37,16) 'groupName'",_jsp_getExpressionFactory().createValueExpression("groupName",java.lang.String.class)));
      // /AddTravelGroup.jsp(37,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(37,16) 'Group Name'",_jsp_getExpressionFactory().createValueExpression("Group Name",java.lang.Object.class)));
      // /AddTravelGroup.jsp(37,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(37,16) 'block mb-1 text-gray-700 font-semibold'",_jsp_getExpressionFactory().createValueExpression("block mb-1 text-gray-700 font-semibold",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f1.setJspId("jsp_1237257437_4");
      int _jspx_eval_h_005foutputLabel_005f1 = _jspx_th_h_005foutputLabel_005f1.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f1 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f1);
    try {
      _jspx_th_h_005finputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(38,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f1.setId("groupName");
      // /AddTravelGroup.jsp(38,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(38,16) '#{travelGroup.groupName}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{travelGroup.groupName}",java.lang.Object.class)));
      // /AddTravelGroup.jsp(38,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(38,16) 'w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400'",_jsp_getExpressionFactory().createValueExpression("w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400",java.lang.String.class)));
      _jspx_th_h_005finputText_005f1.setJspId("jsp_1237257437_5");
      int _jspx_eval_h_005finputText_005f1 = _jspx_th_h_005finputText_005f1.doStartTag();
      if (_jspx_th_h_005finputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f2 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f2);
    try {
      _jspx_th_h_005foutputLabel_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(44,16) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f2.setFor(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(44,16) 'startDate'",_jsp_getExpressionFactory().createValueExpression("startDate",java.lang.String.class)));
      // /AddTravelGroup.jsp(44,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(44,16) 'Start Date'",_jsp_getExpressionFactory().createValueExpression("Start Date",java.lang.Object.class)));
      // /AddTravelGroup.jsp(44,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(44,16) 'block mb-1 text-gray-700 font-semibold'",_jsp_getExpressionFactory().createValueExpression("block mb-1 text-gray-700 font-semibold",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f2.setJspId("jsp_1237257437_6");
      int _jspx_eval_h_005foutputLabel_005f2 = _jspx_th_h_005foutputLabel_005f2.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f2 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f2);
    try {
      _jspx_th_h_005finputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(45,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f2.setId("startDate");
      // /AddTravelGroup.jsp(45,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(45,16) '#{travelGroup.startDate}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{travelGroup.startDate}",java.lang.Object.class)));
      // /AddTravelGroup.jsp(45,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(45,16) 'w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400'",_jsp_getExpressionFactory().createValueExpression("w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400",java.lang.String.class)));
      _jspx_th_h_005finputText_005f2.setJspId("jsp_1237257437_7");
      int _jspx_eval_h_005finputText_005f2 = _jspx_th_h_005finputText_005f2.doStartTag();
      if (_jspx_eval_h_005finputText_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005finputText_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005finputText_005f2);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005fconvertDateTime_005f0(_jspx_th_h_005finputText_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005finputText_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005finputText_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005finputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fconvertDateTime_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005finputText_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:convertDateTime
    com.sun.faces.taglib.jsf_core.ConvertDateTimeTag _jspx_th_f_005fconvertDateTime_005f0 = (com.sun.faces.taglib.jsf_core.ConvertDateTimeTag) _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody.get(com.sun.faces.taglib.jsf_core.ConvertDateTimeTag.class);
    boolean _jspx_th_f_005fconvertDateTime_005f0_reused = false;
    try {
      _jspx_th_f_005fconvertDateTime_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fconvertDateTime_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005finputText_005f2);
      // /AddTravelGroup.jsp(47,20) name = pattern type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_f_005fconvertDateTime_005f0.setPattern(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(47,20) 'yyyy-MM-dd'",_jsp_getExpressionFactory().createValueExpression("yyyy-MM-dd",java.lang.String.class)));
      int _jspx_eval_f_005fconvertDateTime_005f0 = _jspx_th_f_005fconvertDateTime_005f0.doStartTag();
      if (_jspx_th_f_005fconvertDateTime_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody.reuse(_jspx_th_f_005fconvertDateTime_005f0);
      _jspx_th_f_005fconvertDateTime_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fconvertDateTime_005f0, _jsp_getInstanceManager(), _jspx_th_f_005fconvertDateTime_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f3 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f3);
    try {
      _jspx_th_h_005foutputLabel_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(53,16) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f3.setFor(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(53,16) 'endDate'",_jsp_getExpressionFactory().createValueExpression("endDate",java.lang.String.class)));
      // /AddTravelGroup.jsp(53,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(53,16) 'End Date'",_jsp_getExpressionFactory().createValueExpression("End Date",java.lang.Object.class)));
      // /AddTravelGroup.jsp(53,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f3.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(53,16) 'block mb-1 text-gray-700 font-semibold'",_jsp_getExpressionFactory().createValueExpression("block mb-1 text-gray-700 font-semibold",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f3.setJspId("jsp_1237257437_8");
      int _jspx_eval_h_005foutputLabel_005f3 = _jspx_th_h_005foutputLabel_005f3.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f3 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f3);
    try {
      _jspx_th_h_005finputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(54,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f3.setId("endDate");
      // /AddTravelGroup.jsp(54,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(54,16) '#{travelGroup.endDate}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{travelGroup.endDate}",java.lang.Object.class)));
      // /AddTravelGroup.jsp(54,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f3.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(54,16) 'w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400'",_jsp_getExpressionFactory().createValueExpression("w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400",java.lang.String.class)));
      _jspx_th_h_005finputText_005f3.setJspId("jsp_1237257437_9");
      int _jspx_eval_h_005finputText_005f3 = _jspx_th_h_005finputText_005f3.doStartTag();
      if (_jspx_eval_h_005finputText_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005finputText_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005finputText_005f3);
        }
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_f_005fconvertDateTime_005f1(_jspx_th_h_005finputText_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_h_005finputText_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005finputText_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005finputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fconvertDateTime_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005finputText_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:convertDateTime
    com.sun.faces.taglib.jsf_core.ConvertDateTimeTag _jspx_th_f_005fconvertDateTime_005f1 = (com.sun.faces.taglib.jsf_core.ConvertDateTimeTag) _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody.get(com.sun.faces.taglib.jsf_core.ConvertDateTimeTag.class);
    boolean _jspx_th_f_005fconvertDateTime_005f1_reused = false;
    try {
      _jspx_th_f_005fconvertDateTime_005f1.setPageContext(_jspx_page_context);
      _jspx_th_f_005fconvertDateTime_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005finputText_005f3);
      // /AddTravelGroup.jsp(56,20) name = pattern type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_f_005fconvertDateTime_005f1.setPattern(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(56,20) 'yyyy-MM-dd'",_jsp_getExpressionFactory().createValueExpression("yyyy-MM-dd",java.lang.String.class)));
      int _jspx_eval_f_005fconvertDateTime_005f1 = _jspx_th_f_005fconvertDateTime_005f1.doStartTag();
      if (_jspx_th_f_005fconvertDateTime_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005fconvertDateTime_0026_005fpattern_005fnobody.reuse(_jspx_th_f_005fconvertDateTime_005f1);
      _jspx_th_f_005fconvertDateTime_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fconvertDateTime_005f1, _jsp_getInstanceManager(), _jspx_th_f_005fconvertDateTime_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLabel_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLabel
    com.sun.faces.taglib.html_basic.OutputLabelTag _jspx_th_h_005foutputLabel_005f4 = new com.sun.faces.taglib.html_basic.OutputLabelTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLabel_005f4);
    try {
      _jspx_th_h_005foutputLabel_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLabel_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(62,16) name = for type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f4.setFor(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(62,16) 'initialAmount'",_jsp_getExpressionFactory().createValueExpression("initialAmount",java.lang.String.class)));
      // /AddTravelGroup.jsp(62,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(62,16) 'Initial Amount'",_jsp_getExpressionFactory().createValueExpression("Initial Amount",java.lang.Object.class)));
      // /AddTravelGroup.jsp(62,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLabel_005f4.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(62,16) 'block mb-1 text-gray-700 font-semibold'",_jsp_getExpressionFactory().createValueExpression("block mb-1 text-gray-700 font-semibold",java.lang.String.class)));
      _jspx_th_h_005foutputLabel_005f4.setJspId("jsp_1237257437_10");
      int _jspx_eval_h_005foutputLabel_005f4 = _jspx_th_h_005foutputLabel_005f4.doStartTag();
      if (_jspx_th_h_005foutputLabel_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLabel_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f4 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f4);
    try {
      _jspx_th_h_005finputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(63,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f4.setId("initialAmount");
      // /AddTravelGroup.jsp(63,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(63,16) '#{travelGroup.initialAmount}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{travelGroup.initialAmount}",java.lang.Object.class)));
      // /AddTravelGroup.jsp(63,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f4.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(63,16) 'w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400'",_jsp_getExpressionFactory().createValueExpression("w-full p-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-400",java.lang.String.class)));
      _jspx_th_h_005finputText_005f4.setJspId("jsp_1237257437_11");
      int _jspx_eval_h_005finputText_005f4 = _jspx_th_h_005finputText_005f4.doStartTag();
      if (_jspx_th_h_005finputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f0 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f0);
    try {
      _jspx_th_h_005fcommandButton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AddTravelGroup.jsp(69,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(69,16) 'Add Group'",_jsp_getExpressionFactory().createValueExpression("Add Group",java.lang.Object.class)));
      // /AddTravelGroup.jsp(69,16) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/AddTravelGroup.jsp(69,16) '#{userDao.addGroup(travelGroup)}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{userDao.addGroup(travelGroup)}",java.lang.Object.class,new java.lang.Class[] {})));
      // /AddTravelGroup.jsp(69,16) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AddTravelGroup.jsp(69,16) 'bg-green-500 text-white px-6 py-2 rounded hover:bg-green-600 transition'",_jsp_getExpressionFactory().createValueExpression("bg-green-500 text-white px-6 py-2 rounded hover:bg-green-600 transition",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f0.setJspId("jsp_1237257437_12");
      int _jspx_eval_h_005fcommandButton_005f0 = _jspx_th_h_005fcommandButton_005f0.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
