/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-06-03 11:02:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Trip Dashboard</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-black min-h-screen flex items-center justify-center p-6 font-sans\">\r\n");
      out.write("    <div class=\"bg-white max-w-7xl w-full p-8 rounded-md shadow-md text-center overflow-x-auto\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        <header class=\"mb-6\">\r\n");
      out.write("            <h1 class=\"text-3xl font-bold text-green-700\">Trip Dashboard</h1>\r\n");
      out.write("            <p class=\"text-gray-600\">Navigate to different sections</p>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation Buttons -->\r\n");
      out.write("        <div class=\"flex flex-wrap justify-center gap-4\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"showExpenses.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition whitespace-nowrap\">\r\n");
      out.write("                See Expenses\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"showSettlements.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition whitespace-nowrap\">\r\n");
      out.write("                See Settlements\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"AddUser.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition whitespace-nowrap\">\r\n");
      out.write("                Add New User\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"AddTravelGroup.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-yellow-500 text-white rounded hover:bg-yellow-600 transition whitespace-nowrap\">\r\n");
      out.write("                Add New Group\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"AddDailyExpense.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition whitespace-nowrap\">\r\n");
      out.write("                Add Daily Expense\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"AddGroupMembers.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-indigo-500 text-white rounded hover:bg-indigo-600 transition whitespace-nowrap\">\r\n");
      out.write("                Add Group Members\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- ✅ New Navigation Buttons -->\r\n");
      out.write("\r\n");
      out.write("            <a href=\"ShowGroups.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-cyan-500 text-white rounded hover:bg-cyan-600 transition whitespace-nowrap\">\r\n");
      out.write("                Show Groups\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"ShowUsers.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-teal-500 text-white rounded hover:bg-teal-600 transition whitespace-nowrap\">\r\n");
      out.write("                Show Users\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"ShowMembers.jsf\"\r\n");
      out.write("               class=\"px-6 py-2 bg-pink-500 text-white rounded hover:bg-pink-600 transition whitespace-nowrap\">\r\n");
      out.write("                Show Members\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
